--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Ubuntu 12.9-2.pgdg20.04+1)
-- Dumped by pg_dump version 12.9 (Ubuntu 12.9-2.pgdg20.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE number_guess;
--
-- Name: number_guess; Type: DATABASE; Schema: -; Owner: freecodecamp
--

CREATE DATABASE number_guess WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C.UTF-8' LC_CTYPE = 'C.UTF-8';


ALTER DATABASE number_guess OWNER TO freecodecamp;

\connect number_guess

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: game; Type: TABLE; Schema: public; Owner: freecodecamp
--

CREATE TABLE public.game (
    game_id integer NOT NULL,
    player_id integer,
    no_tries integer
);


ALTER TABLE public.game OWNER TO freecodecamp;

--
-- Name: game_game_id_seq; Type: SEQUENCE; Schema: public; Owner: freecodecamp
--

ALTER TABLE public.game ALTER COLUMN game_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player; Type: TABLE; Schema: public; Owner: freecodecamp
--

CREATE TABLE public.player (
    player_id integer NOT NULL,
    player_name character varying(22) NOT NULL
);


ALTER TABLE public.player OWNER TO freecodecamp;

--
-- Name: player_player_id_seq; Type: SEQUENCE; Schema: public; Owner: freecodecamp
--

ALTER TABLE public.player ALTER COLUMN player_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: game; Type: TABLE DATA; Schema: public; Owner: freecodecamp
--

INSERT INTO public.game VALUES (1, 1, 100);
INSERT INTO public.game VALUES (2, NULL, 7);
INSERT INTO public.game VALUES (3, 1, 6);
INSERT INTO public.game VALUES (4, 1, 1);
INSERT INTO public.game VALUES (5, NULL, 16);
INSERT INTO public.game VALUES (6, NULL, 869);
INSERT INTO public.game VALUES (7, NULL, 888);
INSERT INTO public.game VALUES (8, NULL, 354);
INSERT INTO public.game VALUES (9, NULL, 491);
INSERT INTO public.game VALUES (10, NULL, 663);
INSERT INTO public.game VALUES (11, NULL, 381);
INSERT INTO public.game VALUES (12, NULL, 219);
INSERT INTO public.game VALUES (13, NULL, 86);
INSERT INTO public.game VALUES (14, NULL, 315);
INSERT INTO public.game VALUES (15, NULL, 448);
INSERT INTO public.game VALUES (16, NULL, 766);
INSERT INTO public.game VALUES (17, NULL, 476);
INSERT INTO public.game VALUES (18, NULL, 527);
INSERT INTO public.game VALUES (19, NULL, 851);
INSERT INTO public.game VALUES (20, NULL, 797);
INSERT INTO public.game VALUES (21, NULL, 940);
INSERT INTO public.game VALUES (22, NULL, 176);
INSERT INTO public.game VALUES (23, NULL, 830);
INSERT INTO public.game VALUES (24, NULL, 566);
INSERT INTO public.game VALUES (25, NULL, 802);
INSERT INTO public.game VALUES (26, NULL, 195);
INSERT INTO public.game VALUES (27, NULL, 837);
INSERT INTO public.game VALUES (28, NULL, 590);
INSERT INTO public.game VALUES (29, NULL, 366);
INSERT INTO public.game VALUES (30, NULL, 900);
INSERT INTO public.game VALUES (31, NULL, 290);
INSERT INTO public.game VALUES (32, NULL, 218);
INSERT INTO public.game VALUES (33, NULL, 632);
INSERT INTO public.game VALUES (34, NULL, 987);
INSERT INTO public.game VALUES (35, NULL, 452);
INSERT INTO public.game VALUES (36, NULL, 948);
INSERT INTO public.game VALUES (37, NULL, 118);
INSERT INTO public.game VALUES (38, NULL, 883);
INSERT INTO public.game VALUES (39, NULL, 168);
INSERT INTO public.game VALUES (40, NULL, 136);
INSERT INTO public.game VALUES (41, NULL, 764);
INSERT INTO public.game VALUES (42, NULL, 340);
INSERT INTO public.game VALUES (43, NULL, 275);
INSERT INTO public.game VALUES (44, NULL, 8);
INSERT INTO public.game VALUES (45, NULL, 431);
INSERT INTO public.game VALUES (46, NULL, 528);
INSERT INTO public.game VALUES (47, NULL, 83);
INSERT INTO public.game VALUES (48, NULL, 169);
INSERT INTO public.game VALUES (49, NULL, 335);
INSERT INTO public.game VALUES (50, NULL, 598);
INSERT INTO public.game VALUES (51, NULL, 514);
INSERT INTO public.game VALUES (52, NULL, 165);
INSERT INTO public.game VALUES (53, NULL, 590);
INSERT INTO public.game VALUES (54, NULL, 180);
INSERT INTO public.game VALUES (55, NULL, 104);
INSERT INTO public.game VALUES (56, NULL, 561);
INSERT INTO public.game VALUES (57, NULL, 128);
INSERT INTO public.game VALUES (58, NULL, 374);
INSERT INTO public.game VALUES (59, NULL, 62);
INSERT INTO public.game VALUES (60, NULL, 10);
INSERT INTO public.game VALUES (61, NULL, 520);
INSERT INTO public.game VALUES (62, NULL, 659);
INSERT INTO public.game VALUES (63, NULL, 996);
INSERT INTO public.game VALUES (64, NULL, 193);
INSERT INTO public.game VALUES (65, NULL, 516);
INSERT INTO public.game VALUES (66, NULL, 842);
INSERT INTO public.game VALUES (67, NULL, 374);
INSERT INTO public.game VALUES (68, NULL, 204);
INSERT INTO public.game VALUES (69, NULL, 913);
INSERT INTO public.game VALUES (70, NULL, 450);
INSERT INTO public.game VALUES (71, NULL, 120);
INSERT INTO public.game VALUES (72, NULL, 286);
INSERT INTO public.game VALUES (73, NULL, 362);
INSERT INTO public.game VALUES (74, NULL, 466);
INSERT INTO public.game VALUES (75, NULL, 483);
INSERT INTO public.game VALUES (76, NULL, 732);
INSERT INTO public.game VALUES (77, NULL, 755);
INSERT INTO public.game VALUES (78, NULL, 849);
INSERT INTO public.game VALUES (79, NULL, 913);
INSERT INTO public.game VALUES (80, NULL, 14);
INSERT INTO public.game VALUES (81, NULL, 201);
INSERT INTO public.game VALUES (82, NULL, 283);
INSERT INTO public.game VALUES (83, NULL, 39);
INSERT INTO public.game VALUES (84, NULL, 560);
INSERT INTO public.game VALUES (85, NULL, 232);
INSERT INTO public.game VALUES (86, NULL, 524);
INSERT INTO public.game VALUES (87, NULL, 103);
INSERT INTO public.game VALUES (88, NULL, 50);
INSERT INTO public.game VALUES (89, NULL, 704);
INSERT INTO public.game VALUES (90, NULL, 907);
INSERT INTO public.game VALUES (91, NULL, 798);
INSERT INTO public.game VALUES (92, NULL, 250);
INSERT INTO public.game VALUES (93, NULL, 303);
INSERT INTO public.game VALUES (94, NULL, 566);
INSERT INTO public.game VALUES (95, NULL, 105);
INSERT INTO public.game VALUES (96, NULL, 854);
INSERT INTO public.game VALUES (97, NULL, 617);
INSERT INTO public.game VALUES (98, NULL, 666);
INSERT INTO public.game VALUES (99, NULL, 313);
INSERT INTO public.game VALUES (100, NULL, 644);
INSERT INTO public.game VALUES (101, NULL, 778);
INSERT INTO public.game VALUES (102, NULL, 125);
INSERT INTO public.game VALUES (103, NULL, 348);
INSERT INTO public.game VALUES (104, NULL, 654);
INSERT INTO public.game VALUES (105, NULL, 245);
INSERT INTO public.game VALUES (106, NULL, 747);
INSERT INTO public.game VALUES (107, NULL, 502);
INSERT INTO public.game VALUES (108, NULL, 977);
INSERT INTO public.game VALUES (109, NULL, 991);
INSERT INTO public.game VALUES (110, NULL, 821);
INSERT INTO public.game VALUES (111, NULL, 293);
INSERT INTO public.game VALUES (112, NULL, 212);
INSERT INTO public.game VALUES (113, NULL, 134);
INSERT INTO public.game VALUES (114, NULL, 371);
INSERT INTO public.game VALUES (115, NULL, 223);
INSERT INTO public.game VALUES (116, NULL, 358);
INSERT INTO public.game VALUES (117, NULL, 992);
INSERT INTO public.game VALUES (118, NULL, 43);
INSERT INTO public.game VALUES (119, NULL, 502);
INSERT INTO public.game VALUES (120, NULL, 900);
INSERT INTO public.game VALUES (121, NULL, 386);
INSERT INTO public.game VALUES (122, NULL, 309);
INSERT INTO public.game VALUES (123, NULL, 447);
INSERT INTO public.game VALUES (124, NULL, 483);
INSERT INTO public.game VALUES (125, 268, 548);
INSERT INTO public.game VALUES (126, 268, 315);
INSERT INTO public.game VALUES (127, 269, 724);
INSERT INTO public.game VALUES (128, 269, 29);
INSERT INTO public.game VALUES (129, 268, 703);
INSERT INTO public.game VALUES (130, 268, 422);
INSERT INTO public.game VALUES (131, 268, 694);
INSERT INTO public.game VALUES (132, 270, 100);
INSERT INTO public.game VALUES (133, 270, 187);
INSERT INTO public.game VALUES (134, 271, 274);
INSERT INTO public.game VALUES (135, 271, 752);
INSERT INTO public.game VALUES (136, 270, 103);
INSERT INTO public.game VALUES (137, 270, 603);
INSERT INTO public.game VALUES (138, 270, 330);
INSERT INTO public.game VALUES (139, 279, 695);
INSERT INTO public.game VALUES (140, 279, 127);
INSERT INTO public.game VALUES (141, 280, 17);
INSERT INTO public.game VALUES (142, 280, 546);
INSERT INTO public.game VALUES (143, 279, 893);
INSERT INTO public.game VALUES (144, 279, 638);
INSERT INTO public.game VALUES (145, 279, 52);


--
-- Data for Name: player; Type: TABLE DATA; Schema: public; Owner: freecodecamp
--

INSERT INTO public.player VALUES (1, 'Javier');
INSERT INTO public.player VALUES (2, '');
INSERT INTO public.player VALUES (3, '');
INSERT INTO public.player VALUES (4, '');
INSERT INTO public.player VALUES (5, '');
INSERT INTO public.player VALUES (6, '');
INSERT INTO public.player VALUES (7, '');
INSERT INTO public.player VALUES (8, '');
INSERT INTO public.player VALUES (9, '');
INSERT INTO public.player VALUES (10, '');
INSERT INTO public.player VALUES (11, '');
INSERT INTO public.player VALUES (12, '');
INSERT INTO public.player VALUES (13, '');
INSERT INTO public.player VALUES (14, '');
INSERT INTO public.player VALUES (15, '');
INSERT INTO public.player VALUES (16, '');
INSERT INTO public.player VALUES (17, '');
INSERT INTO public.player VALUES (18, '');
INSERT INTO public.player VALUES (19, '');
INSERT INTO public.player VALUES (20, '');
INSERT INTO public.player VALUES (21, '');
INSERT INTO public.player VALUES (22, '');
INSERT INTO public.player VALUES (23, '');
INSERT INTO public.player VALUES (24, '');
INSERT INTO public.player VALUES (25, '');
INSERT INTO public.player VALUES (26, '');
INSERT INTO public.player VALUES (27, '');
INSERT INTO public.player VALUES (28, '');
INSERT INTO public.player VALUES (29, '');
INSERT INTO public.player VALUES (30, '');
INSERT INTO public.player VALUES (31, '');
INSERT INTO public.player VALUES (32, '');
INSERT INTO public.player VALUES (33, '');
INSERT INTO public.player VALUES (34, '');
INSERT INTO public.player VALUES (35, '');
INSERT INTO public.player VALUES (36, '');
INSERT INTO public.player VALUES (37, '');
INSERT INTO public.player VALUES (38, '');
INSERT INTO public.player VALUES (39, '');
INSERT INTO public.player VALUES (40, '');
INSERT INTO public.player VALUES (41, '');
INSERT INTO public.player VALUES (42, '');
INSERT INTO public.player VALUES (43, '');
INSERT INTO public.player VALUES (44, '');
INSERT INTO public.player VALUES (45, 'Jose');
INSERT INTO public.player VALUES (46, 'Jose');
INSERT INTO public.player VALUES (47, 'user_1672532856647');
INSERT INTO public.player VALUES (48, 'user_1672532856647');
INSERT INTO public.player VALUES (49, 'user_1672532856646');
INSERT INTO public.player VALUES (50, 'user_1672532856646');
INSERT INTO public.player VALUES (51, 'user_1672532856647');
INSERT INTO public.player VALUES (52, 'user_1672532856647');
INSERT INTO public.player VALUES (53, 'user_1672532856647');
INSERT INTO public.player VALUES (54, 'user_1672532997632');
INSERT INTO public.player VALUES (55, 'user_1672532997632');
INSERT INTO public.player VALUES (56, 'user_1672532997631');
INSERT INTO public.player VALUES (57, 'user_1672532997631');
INSERT INTO public.player VALUES (58, 'user_1672532997632');
INSERT INTO public.player VALUES (59, 'user_1672532997632');
INSERT INTO public.player VALUES (60, 'user_1672532997632');
INSERT INTO public.player VALUES (61, 'user_1672533025223');
INSERT INTO public.player VALUES (62, 'user_1672533025223');
INSERT INTO public.player VALUES (63, 'user_1672533025222');
INSERT INTO public.player VALUES (64, 'user_1672533025222');
INSERT INTO public.player VALUES (65, 'user_1672533025223');
INSERT INTO public.player VALUES (66, 'user_1672533025223');
INSERT INTO public.player VALUES (67, 'user_1672533025223');
INSERT INTO public.player VALUES (68, 'user_1672533074359');
INSERT INTO public.player VALUES (69, 'user_1672533074359');
INSERT INTO public.player VALUES (70, 'user_1672533074358');
INSERT INTO public.player VALUES (71, 'user_1672533074358');
INSERT INTO public.player VALUES (72, 'user_1672533074359');
INSERT INTO public.player VALUES (73, 'user_1672533074359');
INSERT INTO public.player VALUES (74, 'user_1672533074359');
INSERT INTO public.player VALUES (75, 'user_1672533264774');
INSERT INTO public.player VALUES (76, 'user_1672533264774');
INSERT INTO public.player VALUES (77, 'user_1672533264773');
INSERT INTO public.player VALUES (78, 'user_1672533264773');
INSERT INTO public.player VALUES (79, 'user_1672533264774');
INSERT INTO public.player VALUES (80, 'user_1672533264774');
INSERT INTO public.player VALUES (81, 'user_1672533264774');
INSERT INTO public.player VALUES (82, 'user_1672534152989');
INSERT INTO public.player VALUES (83, 'user_1672534152989');
INSERT INTO public.player VALUES (84, 'user_1672534152988');
INSERT INTO public.player VALUES (85, 'user_1672534152988');
INSERT INTO public.player VALUES (86, 'user_1672534152989');
INSERT INTO public.player VALUES (87, 'user_1672534152989');
INSERT INTO public.player VALUES (88, 'user_1672534152989');
INSERT INTO public.player VALUES (89, 'user_1672534247255');
INSERT INTO public.player VALUES (90, 'user_1672534247255');
INSERT INTO public.player VALUES (91, 'user_1672534247254');
INSERT INTO public.player VALUES (92, 'user_1672534247254');
INSERT INTO public.player VALUES (93, 'user_1672534247255');
INSERT INTO public.player VALUES (94, 'user_1672534247255');
INSERT INTO public.player VALUES (95, 'user_1672534247255');
INSERT INTO public.player VALUES (96, 'user_1672534393196');
INSERT INTO public.player VALUES (97, 'user_1672534393196');
INSERT INTO public.player VALUES (98, 'user_1672534393195');
INSERT INTO public.player VALUES (99, 'user_1672534393195');
INSERT INTO public.player VALUES (100, 'user_1672534393196');
INSERT INTO public.player VALUES (101, 'user_1672534393196');
INSERT INTO public.player VALUES (102, 'user_1672534393196');
INSERT INTO public.player VALUES (103, 'user_1672534498276');
INSERT INTO public.player VALUES (104, 'user_1672534498276');
INSERT INTO public.player VALUES (105, 'user_1672534498275');
INSERT INTO public.player VALUES (106, 'user_1672534498275');
INSERT INTO public.player VALUES (107, 'user_1672534498276');
INSERT INTO public.player VALUES (108, 'user_1672534498276');
INSERT INTO public.player VALUES (109, 'user_1672534498276');
INSERT INTO public.player VALUES (136, 'user_1672693148392');
INSERT INTO public.player VALUES (137, 'user_1672693148392');
INSERT INTO public.player VALUES (138, 'user_1672693148391');
INSERT INTO public.player VALUES (139, 'user_1672693148391');
INSERT INTO public.player VALUES (140, 'user_1672693148392');
INSERT INTO public.player VALUES (141, 'user_1672693148392');
INSERT INTO public.player VALUES (142, 'user_1672693148392');
INSERT INTO public.player VALUES (143, '');
INSERT INTO public.player VALUES (144, '');
INSERT INTO public.player VALUES (145, '');
INSERT INTO public.player VALUES (146, '');
INSERT INTO public.player VALUES (147, '');
INSERT INTO public.player VALUES (148, '');
INSERT INTO public.player VALUES (149, '');
INSERT INTO public.player VALUES (150, '');
INSERT INTO public.player VALUES (151, '');
INSERT INTO public.player VALUES (152, '');
INSERT INTO public.player VALUES (153, '');
INSERT INTO public.player VALUES (154, '');
INSERT INTO public.player VALUES (155, '');
INSERT INTO public.player VALUES (156, '');
INSERT INTO public.player VALUES (157, '');
INSERT INTO public.player VALUES (158, '');
INSERT INTO public.player VALUES (159, '');
INSERT INTO public.player VALUES (160, '');
INSERT INTO public.player VALUES (161, '');
INSERT INTO public.player VALUES (162, '');
INSERT INTO public.player VALUES (163, '');
INSERT INTO public.player VALUES (164, '');
INSERT INTO public.player VALUES (165, '');
INSERT INTO public.player VALUES (166, '');
INSERT INTO public.player VALUES (167, '');
INSERT INTO public.player VALUES (168, '');
INSERT INTO public.player VALUES (169, '');
INSERT INTO public.player VALUES (170, '');
INSERT INTO public.player VALUES (171, '');
INSERT INTO public.player VALUES (172, '');
INSERT INTO public.player VALUES (173, '');
INSERT INTO public.player VALUES (174, '');
INSERT INTO public.player VALUES (175, '');
INSERT INTO public.player VALUES (176, '');
INSERT INTO public.player VALUES (177, '');
INSERT INTO public.player VALUES (178, '');
INSERT INTO public.player VALUES (179, '');
INSERT INTO public.player VALUES (180, '');
INSERT INTO public.player VALUES (181, '');
INSERT INTO public.player VALUES (182, '');
INSERT INTO public.player VALUES (183, '');
INSERT INTO public.player VALUES (184, '');
INSERT INTO public.player VALUES (185, '');
INSERT INTO public.player VALUES (186, '');
INSERT INTO public.player VALUES (187, '');
INSERT INTO public.player VALUES (188, '');
INSERT INTO public.player VALUES (189, '');
INSERT INTO public.player VALUES (190, '');
INSERT INTO public.player VALUES (191, '');
INSERT INTO public.player VALUES (192, '');
INSERT INTO public.player VALUES (193, '');
INSERT INTO public.player VALUES (194, '');
INSERT INTO public.player VALUES (195, '');
INSERT INTO public.player VALUES (196, '');
INSERT INTO public.player VALUES (197, '');
INSERT INTO public.player VALUES (198, '');
INSERT INTO public.player VALUES (199, '');
INSERT INTO public.player VALUES (200, '');
INSERT INTO public.player VALUES (201, '');
INSERT INTO public.player VALUES (202, '');
INSERT INTO public.player VALUES (203, '');
INSERT INTO public.player VALUES (204, '');
INSERT INTO public.player VALUES (205, '');
INSERT INTO public.player VALUES (206, '');
INSERT INTO public.player VALUES (207, '');
INSERT INTO public.player VALUES (208, '');
INSERT INTO public.player VALUES (209, '');
INSERT INTO public.player VALUES (210, '');
INSERT INTO public.player VALUES (211, '');
INSERT INTO public.player VALUES (212, '');
INSERT INTO public.player VALUES (213, '');
INSERT INTO public.player VALUES (214, '');
INSERT INTO public.player VALUES (215, '');
INSERT INTO public.player VALUES (216, '');
INSERT INTO public.player VALUES (217, '');
INSERT INTO public.player VALUES (218, '');
INSERT INTO public.player VALUES (219, '');
INSERT INTO public.player VALUES (220, '');
INSERT INTO public.player VALUES (221, '');
INSERT INTO public.player VALUES (222, '');
INSERT INTO public.player VALUES (223, '');
INSERT INTO public.player VALUES (224, '');
INSERT INTO public.player VALUES (225, '');
INSERT INTO public.player VALUES (226, '');
INSERT INTO public.player VALUES (227, '');
INSERT INTO public.player VALUES (228, '');
INSERT INTO public.player VALUES (229, '');
INSERT INTO public.player VALUES (230, '');
INSERT INTO public.player VALUES (231, '');
INSERT INTO public.player VALUES (232, '');
INSERT INTO public.player VALUES (233, '');
INSERT INTO public.player VALUES (234, '');
INSERT INTO public.player VALUES (235, '');
INSERT INTO public.player VALUES (236, '');
INSERT INTO public.player VALUES (237, '');
INSERT INTO public.player VALUES (238, '');
INSERT INTO public.player VALUES (239, '');
INSERT INTO public.player VALUES (240, '');
INSERT INTO public.player VALUES (241, '');
INSERT INTO public.player VALUES (242, '');
INSERT INTO public.player VALUES (243, '');
INSERT INTO public.player VALUES (244, '');
INSERT INTO public.player VALUES (245, '');
INSERT INTO public.player VALUES (246, '');
INSERT INTO public.player VALUES (247, '');
INSERT INTO public.player VALUES (248, '');
INSERT INTO public.player VALUES (249, '');
INSERT INTO public.player VALUES (250, '');
INSERT INTO public.player VALUES (251, '');
INSERT INTO public.player VALUES (252, '');
INSERT INTO public.player VALUES (253, '');
INSERT INTO public.player VALUES (254, '');
INSERT INTO public.player VALUES (255, '');
INSERT INTO public.player VALUES (256, '');
INSERT INTO public.player VALUES (257, '');
INSERT INTO public.player VALUES (258, '');
INSERT INTO public.player VALUES (259, '');
INSERT INTO public.player VALUES (260, '');
INSERT INTO public.player VALUES (261, '');
INSERT INTO public.player VALUES (262, '');
INSERT INTO public.player VALUES (263, '');
INSERT INTO public.player VALUES (264, '');
INSERT INTO public.player VALUES (265, '');
INSERT INTO public.player VALUES (266, '');
INSERT INTO public.player VALUES (267, '');
INSERT INTO public.player VALUES (268, 'user_1672698583749');
INSERT INTO public.player VALUES (269, 'user_1672698583748');
INSERT INTO public.player VALUES (270, 'user_1672698599995');
INSERT INTO public.player VALUES (271, 'user_1672698599994');
INSERT INTO public.player VALUES (272, 'user_1672698648897');
INSERT INTO public.player VALUES (273, 'user_1672698648897');
INSERT INTO public.player VALUES (274, 'user_1672698648896');
INSERT INTO public.player VALUES (275, 'user_1672698648896');
INSERT INTO public.player VALUES (276, 'user_1672698648897');
INSERT INTO public.player VALUES (277, 'user_1672698648897');
INSERT INTO public.player VALUES (278, 'user_1672698648897');
INSERT INTO public.player VALUES (279, 'user_1672698666365');
INSERT INTO public.player VALUES (280, 'user_1672698666364');


--
-- Name: game_game_id_seq; Type: SEQUENCE SET; Schema: public; Owner: freecodecamp
--

SELECT pg_catalog.setval('public.game_game_id_seq', 145, true);


--
-- Name: player_player_id_seq; Type: SEQUENCE SET; Schema: public; Owner: freecodecamp
--

SELECT pg_catalog.setval('public.player_player_id_seq', 280, true);


--
-- Name: game game_pkey; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT game_pkey PRIMARY KEY (game_id);


--
-- Name: player player_pkey; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (player_id);


--
-- Name: game fk_player_id; Type: FK CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.game
    ADD CONSTRAINT fk_player_id FOREIGN KEY (player_id) REFERENCES public.player(player_id);


--
-- PostgreSQL database dump complete
--

